# Generated by Django 5.2.3 on 2025-06-22 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="优惠名称")),
                (
                    "code",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="优惠码"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("percent", "百分比折扣"), ("fixed", "固定金额折扣")],
                        max_length=100,
                        verbose_name="优惠类型",
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="优惠值"
                    ),
                ),
                (
                    "min_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="最低消费",
                    ),
                ),
                (
                    "max_uses",
                    models.IntegerField(default=1, verbose_name="最大使用次数"),
                ),
                (
                    "users_count",
                    models.IntegerField(default=0, verbose_name="用户数量"),
                ),
                ("start_date", models.DateTimeField(verbose_name="开始时间")),
                ("end_date", models.DateTimeField(verbose_name="结束时间")),
                ("active", models.BooleanField(default=True, verbose_name="是否激活")),
            ],
        ),
        migrations.CreateModel(
            name="UserCoupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("used", models.BooleanField(default=False, verbose_name="是否使用")),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="使用时间"
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="promotions.coupon",
                        verbose_name="优惠券",
                    ),
                ),
            ],
        ),
    ]
