# Generated by Django 5.2.3 on 2025-07-27 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_no",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="支付单号"
                    ),
                ),
                (
                    "transaction_no",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="交易单号"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("alipay", "支付宝"), ("wechat", "微信")],
                        max_length=20,
                        verbose_name="支付方式",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "待支付"),
                            ("paying", "支付中"),
                            ("paid", "已支付"),
                            ("failed", "支付失败"),
                            ("refunding", "退款中"),
                            ("refunded", "已退款"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="支付状态",
                    ),
                ),
                (
                    "fee",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="手续费"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="支付金额"
                    ),
                ),
                (
                    "currency",
                    models.CharField(default="CNY", max_length=10, verbose_name="货币"),
                ),
                ("client_ip", models.CharField(max_length=20, verbose_name="客户端IP")),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="支付时间"
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="orders.order",
                        verbose_name="订单",
                    ),
                ),
            ],
            options={
                "verbose_name": "支付",
                "verbose_name_plural": "支付",
                "db_table": "ms_payment",
                "ordering": ["-create_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=20, verbose_name="操作")),
                ("request", models.TextField(verbose_name="请求")),
                ("response", models.TextField(verbose_name="响应")),
                (
                    "success",
                    models.BooleanField(default=False, verbose_name="是否成功"),
                ),
                (
                    "create_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="payments.payment",
                        verbose_name="支付",
                    ),
                ),
            ],
            options={
                "verbose_name": "支付日志",
                "verbose_name_plural": "支付日志",
                "db_table": "ms_payment_log",
                "ordering": ["-create_at"],
            },
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "refund_no",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="退款单号"
                    ),
                ),
                (
                    "transaction_no",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="交易单号"
                    ),
                ),
                (
                    "refund_status",
                    models.CharField(
                        choices=[
                            ("pending", "待退款"),
                            ("refunding", "退款中"),
                            ("refunded", "已退款"),
                            ("failed", "退款失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="退款状态",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="退款金额"
                    ),
                ),
                ("reason", models.CharField(max_length=200, verbose_name="退款原因")),
                (
                    "currency",
                    models.CharField(default="CNY", max_length=10, verbose_name="货币"),
                ),
                (
                    "refunded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="退款时间"
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "faild_reason",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="退款失败原因",
                    ),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refund",
                        to="payments.payment",
                        verbose_name="支付",
                    ),
                ),
            ],
            options={
                "verbose_name": "退款",
                "verbose_name_plural": "退款",
                "db_table": "ms_refund",
                "ordering": ["-create_at"],
            },
        ),
    ]
