# Generated by Django 5.2.3 on 2025-06-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_managers_user_user_type_alter_user_groups_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientUser",
            fields=[],
            options={
                "verbose_name": "普通用户",
                "verbose_name_plural": "普通用户",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.user",),
        ),
        migrations.CreateModel(
            name="ManagerUser",
            fields=[],
            options={
                "verbose_name": "后台用户",
                "verbose_name_plural": "后台用户",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.user",),
        ),
        migrations.AddField(
            model_name="user",
            name="nickname",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="昵称"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avator",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatar", verbose_name="头像"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="邮箱"),
        ),
        migrations.AlterField(
            model_name="user",
            name="mobile",
            field=models.CharField(
                blank=True, max_length=11, null=True, unique=True, verbose_name="手机号"
            ),
        ),
    ]
