# Generated by Django 5.2.3 on 2025-06-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_clientuser_manageruser_user_nickname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="score",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="积分"
            ),
        ),
    ]
