# Generated by Django 5.2.3 on 2025-06-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True, default="", max_length=30, verbose_name="用户名"
            ),
        ),
    ]
