# Generated by Django 5.2.3 on 2025-06-22 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reviews", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.user",
                verbose_name="用户",
            ),
        ),
        migrations.AddField(
            model_name="reviewreply",
            name="review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="reviews.review",
                verbose_name="评论",
            ),
        ),
        migrations.AddField(
            model_name="reviewreply",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.user",
                verbose_name="用户",
            ),
        ),
    ]
