# Generated by Django 5.2.3 on 2025-07-18 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordrer_number', models.CharField(max_length=20, unique=True, verbose_name='订单号')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('shipping', '发货中'), ('delivered', '已送达'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='订单状态')),
                ('payment_method', models.CharField(max_length=20, verbose_name='支付方式')),
                ('payment_time', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('shipping_time', models.DateTimeField(blank=True, null=True, verbose_name='发货时间')),
                ('delivery_time', models.DateTimeField(blank=True, null=True, verbose_name='送达时间')),
                ('completion_time', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总价')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='优惠')),
                ('shipping_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='运费')),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='实付金额')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.address', verbose_name='地址')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'ms_order',
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='商品名称')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('sub_total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总价')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='订单')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productsku', verbose_name='商品SKU')),
            ],
            options={
                'verbose_name': '订单商品',
                'verbose_name_plural': '订单商品',
                'db_table': 'ms_order_item',
                'ordering': ['-create_at'],
            },
        ),
    ]
