# Generated by Django 5.2.3 on 2025-07-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='desc',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='属性解释'),
        ),
    ]
