# Generated by Django 5.2.3 on 2025-07-13 16:41

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_category_desc_category_lft_category_rght_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="attributes",
            field=models.ManyToManyField(
                blank=True,
                related_name="categories",
                to="products.productattribute",
                verbose_name="允许的SKU属性",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="products.category",
                verbose_name="父级类别",
            ),
        ),
        migrations.AlterField(
            model_name="productsku",
            name="stock",
            field=models.PositiveIntegerField(default=0, verbose_name="SKU库存"),
        ),
        migrations.CreateModel(
            name="ProductSKUAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sku_attributes",
                        to="products.productattribute",
                        verbose_name="属性",
                    ),
                ),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sku_attributes",
                        to="products.productsku",
                        verbose_name="SKU",
                    ),
                ),
                (
                    "value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sku_attributes",
                        to="products.productattributevalue",
                        verbose_name="属性值",
                    ),
                ),
            ],
            options={
                "verbose_name": "SKU属性",
                "verbose_name_plural": "SKU属性",
                "unique_together": {("sku", "attribute")},
            },
        ),
        migrations.AlterField(
            model_name="productsku",
            name="attributes",
            field=models.ManyToManyField(
                related_name="skus",
                through="products.ProductSKUAttribute",
                to="products.productattributevalue",
                verbose_name="SKU属性",
            ),
        ),
    ]
