# Generated by Django 5.2.3 on 2025-07-17 15:43

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_category_desc_category_lft_category_rght_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="attributes",
            field=models.ManyToManyField(
                blank=True,
                related_name="categories",
                to="products.productattribute",
                verbose_name="允许的SKU属性",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="products.category",
                verbose_name="父级类别",
            ),
        ),
        migrations.AlterField(
            model_name="productsku",
            name="attributes",
            field=models.ManyToManyField(
                related_name="attribute_skus",
                to="products.productattributevalue",
                verbose_name="SKU属性",
            ),
        ),
        migrations.AlterField(
            model_name="productsku",
            name="stock",
            field=models.PositiveIntegerField(default=0, verbose_name="SKU库存"),
        ),
    ]
